# Generated by Django 2.0.6 on 2018-12-31 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='downloaded',
            field=models.BooleanField(default=False, verbose_name='Downloaded?'),
        ),
    ]
