# Generated by Django 2.0.6 on 2019-07-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunes', '0003_auto_20190601_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='documents')),
            ],
        ),
    ]
