# Generated by Django 2.0.6 on 2019-07-09 10:13

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunes', '0004_songdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='songdocument',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='songdocument',
            name='document_two',
            field=models.FileField(blank=True, null=True, upload_to='documents'),
        ),
    ]
