# Generated by Django 2.0.6 on 2020-10-29 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunes', '0006_mediafile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_created=True)),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
            ],
        ),
        migrations.RemoveField(
            model_name='youtubevideo',
            name='moods',
        ),
        migrations.RemoveField(
            model_name='youtubevideo',
            name='predicted_moods',
        ),
    ]
